### ISSUE TITLE
Json does not include path to image

### ISSUE THREAD

**Issue by almoreau** [ed7n/jcard-template#1]
Hi,
Not really an issue, but the json doesn't store the path to the chosen picture (stored locally on my computer). 
So when i love the json, th picture is (obviously) not loaded.
 Could it be possible to add this feature?

**Comment by BrendonIrwan** [comment]
Hello. Apologies for the late response.

Paths to local files are actually faked out for privacy reasons, so it is impossible to add this feature.

I will add a duplicate cover image field in the next release to make loading more convenient.

**Comment by BrendonIrwan** [comment]
Closing this as the addition is complete.
